// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlgen

import (
	"time"
)

type Comment struct {
	Id              int64     `json:"id"`
	TextContent     string    `json:"text_content"`
	CreatedAt       time.Time `json:"created_at"`
	AuthorId        int64     `json:"author_id"`
	PostId          int64     `json:"post_id"`
	ParentCommentId *int64    `json:"parent_comment_id"`
}

type Post struct {
	Id          int64     `json:"id"`
	Title       string    `json:"title"`
	Content     *string   `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	AuthorId    int64     `json:"author_id"`
	SubredditId int64     `json:"subreddit_id"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type Subreddit struct {
	Id          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	CreatorId   *int64    `json:"creator_id"`
}

type User struct {
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type UserSubscription struct {
	UserId      int64     `json:"user_id"`
	SubredditId int64     `json:"subreddit_id"`
	CreatedAt   time.Time `json:"created_at"`
}
